### ISSUE TITLE
Is broken after rotation

### ISSUE THREAD

**Issue by Gargo** [sachin21v/SlidingPanel#1]
just use this panel and rotate the device - you will see some problems with layout

**Comment by sachin21v** [comment]
Issue is fixed.
If still find. Please let me know.

**Comment by ghost** [comment]
Hi,  I am still getting this issue in my integration. I have used the latest source files. If i rotate from portrait to landscape in any viewcontroller, the layout is fine for that controller. But while still in landscape, i move to other slidemenu controllers, the layour is all messed up.

Can you please let me know how to fix this?
